In [2]:
import numpy as np
import torch
import tensorflow as tf

In [6]:
#Câu 1: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor từ danh sách 1 chiều?

list_1D = [1, 2, 3, 4, 5, 6]

array_1D = np.array(list_1D)
tensor_torch_1D = torch.tensor(list_1D)
tensor_tensorflow_1D = tf.convert_to_tensor(list_1D)

print("Mảng NumPy: ", array_1D, type(array_1D))
print("Tensor Torch: ", tensor_torch_1D)
print("Tensor TensorFlow: ", tensor_tensorflow_1D)

Mảng NumPy:  [1 2 3 4 5 6] <class 'numpy.ndarray'>
Tensor Torch:  tensor([1, 2, 3, 4, 5, 6])
Tensor TensorFlow:  tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [10]:
#Câu 2: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor từ danh sách 2
#chiều. Sau đó thực hiện kiểm tra thuộc tính shape, dtype, type, device từ các array, tensor vừa tạo?

#Array NumPy
list_2D = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

array_2D = np.array(list_2D)
print("Hình dạng của mảng: ", array_2D.shape)
print("Kiểu dữ liệu: ", array_2D.dtype)
print("Loại của mảng: ", type(array_2D))
print("Mảng: \n", array_2D)


Hình dạng của mảng:  (3, 3)
Kiểu dữ liệu:  int32
Loại của mảng:  <class 'numpy.ndarray'>
Mảng: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#Tensor Torch
tensor_torch_2D = torch.tensor(list_2D)
print("Hình dạng của Tensor: ", tensor_torch_2D.shape)
print("Kiểu dữ liệu: ", tensor_torch_2D.dtype)
print("Loại của Tensor: ", type(tensor_torch_2D))
print("Thiết bị lưu trữ của Tensor: ", tensor_torch_2D.device)
print("Tensor: \n", tensor_torch_2D)

Hình dạng của Tensor:  torch.Size([3, 3])
Kiểu dữ liệu:  torch.int64
Loại của Tensor:  <class 'torch.Tensor'>
Thiết bị lưu trữ của Tensor:  cpu
Tensor: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [12]:
#Tensor tensorFlow
tensor_tensorflow_2D = tf.constant(list_2D)
print("Hình dạng của Tensor: ", tensor_tensorflow_2D.shape)
print("Kiểu dữ liệu: ", tensor_tensorflow_2D.dtype)
print("Loại của Tensor: ", type(tensor_tensorflow_2D))
print("Thiết bị lưu trữ của Tensor: ", tensor_tensorflow_2D.device)
print("Tensor: \n", tensor_tensorflow_2D)

Hình dạng của Tensor:  (3, 3)
Kiểu dữ liệu:  <dtype: 'int32'>
Loại của Tensor:  <class 'tensorflow.python.framework.ops.EagerTensor'>
Thiết bị lưu trữ của Tensor:  /job:localhost/replica:0/task:0/device:CPU:0
Tensor: 
 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
