In [ ]:
# Chuyển vị bằng numpy
import numpy as np

# Tạo array 2D
arr_1 = np.array([[1, 2], [3, 4]])

# Chuyển vị array
# Cách 1: Sử dụng hàm np.transpose()
arr_transposed_1 = np.transpose(arr_1)

# Cách 2: Sử dụng toán tử T
arr_transposed_2 = arr_1.T

# In ra màn hình
print("Array ban đầu: \n", arr_1)
print("Array chuyển vị bằng cách 1: \n", arr_transposed_1)
print("Array chuyển vị bằng cách 2: \n", arr_transposed_2)

In [ ]:
# Chuyển vị bằng pytorch
import torch

# Tạo tensor 2D
tensor_1 = torch.tensor([[1, 2], [3, 4]])

# Chuyển vị tensor
# Cách 1: Sử dụng hàm torch.t()
tensor_transposed_1 = torch.t(tensor_1)

# Cách 2: Sử dụng hàm torch.transpose()
# torch . transpose (input , dim0 , dim1)
# Kết quả trả về là một tensor mới là kết quả của phép chuyển vị. Trong đó:
# • input: Tensor cần được chuyển vị.
# • dim0, dim1: Các chiều được chọn để thực hiện chuyển vị.
tensor_transposed_2 = torch.transpose(tensor_1, 0, 1)

# In ra màn hình
print("Tensor ban đầu: \n", tensor_1)
print("Tensor chuyển vị cách 1: \n", tensor_transposed_1)
print("Tensor chuyển vị cách 2: \n", tensor_transposed_2)

In [ ]:
# Chuyển vị bằng tensorflow
import tensorflow as tf

# Tạo tensorflow 2D
tensor_1 = tf.constant([[1, 2], [3, 4]])

#Chuyển vị tensor
tensor_transposed = tf.transpose(tensor_1)

#In ra màn hình
print("Tensor ban đầu: \n", tensor_1)
print("Tensor sau khi chuyển vị: \n", tensor_transposed)

Summation
np.sum (a, axis = None, dtype = None, keepdims = False, initial =0, where = True)
Trong đó:
• a: Mảng đầu vào.
• axis: (Tùy chọn) Chiều hoặc các chiều trên đó tổng sẽ được thực hiện. Mặc định là None, tức là
tổng của tất cả các phần tử trong mảng.
• dtype: (Tùy chọn) Kiểu dữ liệu của kết quả.
• keepdims: (Tùy chọn) Nếu là True, giữ chiều của mảng kết quả (nếu có) giống với chiều của mảng
đầu vào.
• initial: (Tùy chọn) Giá trị khởi tạo cho tổng.
• where: (Tùy chọn) Một mảng Boolean chỉ định vị trí các phần tử được sử dụng trong phép toán.


In [ ]:
# Numpy code
import numpy as np

# Tạo mảng 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Tính tổng tất cả các phần tử trong mảng
total_sum = np.sum(arr)

# Tính tổng theo cột (chiều dọc)
column_sum = np.sum(arr, axis = 0)

# Tính tổng theo hàng (chiều ngang)
row_sum = np.sum(arr, axis = 1)

# In ra màn hình
print("Mảng: \n", arr)
print("Tổng tất cả các phần tử trong mảng: \n", total_sum)
print("Tổng theo cột: \n", column_sum)
print("Tổng theo hàng: \n", row_sum)

In [ ]:
# Pytorch code
import torch

# Tạo tensor 2D
tensor_1 = torch.tensor([[1, 2], [3, 4]])

# Tính tổng tensor
tensor_sum = torch.sum(tensor_1)

# Tính tổng tensor theo cột axis = 0
tensor_sum_axis_0 = torch.sum(tensor_1, axis = 0)

# Tính tổng tensor theo hàng axis = 1
tensor_sum_axis_1 = torch.sum(tensor_1, axis = 1)

# In ra màn hình
print("tensor: \n", tensor_1)
print("Tổng các phần tử trong tensor: \n", tensor_sum)
print("Tổng theo cột: \n", tensor_sum_axis_0)
print("Tổng theo hàng: \n", tensor_sum_axis_1)

In [7]:
# Tensorflow code
import tensorflow as tf

# Tạo tensor 2D
tensor_1 = tf.constant([[1, 2], [3, 4]])

# Tính tổng tensor
tensor_sum = tf.reduce_sum(tensor_1)

# Tính tổng tensor theo cột axis = 0
tensor_sum_axis_0 = tf.reduce_sum(tensor_1, axis = 0)

# Tính tổng tensor theo hàng axis = 1
tensor_sum_axis_1 = tf.reduce_sum(tensor_1, axis = 1)

# In ra màn hình
print("tensor: \n", tensor_1)
print("Tổng các phần tử trong tensor: \n", tensor_sum)
print("Tổng theo cột: \n", tensor_sum_axis_0)
print("Tổng theo hàng: \n", tensor_sum_axis_1)   

tensor: 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tổng các phần tử trong tensor: 
 tf.Tensor(10, shape=(), dtype=int32)
Tổng theo cột: 
 tf.Tensor([4 6], shape=(2,), dtype=int32)
Tổng theo hàng: 
 tf.Tensor([3 7], shape=(2,), dtype=int32)


In [20]:
# Câu 1: Viết chương trình tạo hai Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số
# nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 4). Sau đó chuyển vị array, tensor thứ 2
# và thực hiện phép nhân matrix multiplication. Lưu ý: sử dụng seed=2024

import numpy as np
import torch
import tensorflow as tf

# Set seed = 2024
SEED = 2024
np.random.seed(SEED)
torch.manual_seed(SEED)
tf.random.set_seed(SEED)

# Tạo 2 Numpy array, Pytorch tensor, Tensorflow tensor với giá trị ngẫu nhiên
np_array_1 = np.random.randint(-10, 10, size=(3, 4))
np_array_2 = np.random.randint(-10, 10, size=(3, 4))

torch_tensor_1 = torch.randint(-10, 10, size=(3, 4))
torch_tensor_2 = torch.randint(-10, 10, size=(3, 4))

tf_tensor_1 = tf.random.uniform(minval=-10, maxval=10, shape=(3, 4))
tf_tensor_2 = tf.random.uniform(minval=-10, maxval=10, shape=(3, 4))

# Chuyển vị arr, tensor thứ 2
np_array_transpose = np.transpose(np_array_2)
torch_tensor_transpose = torch.transpose(torch_tensor_2, 0, 1)
tf_tensor_transpose = tf.transpose(tf_tensor_2)

# Tính tổng của toàn bộ tensor, array, tiếp theo tính tổng theo
# chiều dọc, chiều ngang
np_matmul = np.matmul(np_array_1, np_array_transpose)
torch_matmul = torch.matmul(torch_tensor_1, torch_tensor_transpose)
tf_matmul = tf.matmul(tf_tensor_1, tf_tensor_transpose)

print(np_matmul)
print("----------------------------")
print(torch_matmul)
print("----------------------------")
print(tf_matmul)

[[-80 -46 128]
 [-33 -30  67]
 [-25 -25  42]]
----------------------------
tensor([[  22,   36,  -62],
        [ -89,  163,   99],
        [  87, -180, -148]])
----------------------------
tf.Tensor(
[[-36.226315 -17.063108 -62.29872 ]
 [ 21.901602  -9.125889  61.553036]
 [ 21.210764 -70.07383   74.909744]], shape=(3, 3), dtype=float32)


: 

In [18]:
# Câu 2: Viết chương trình tạo một Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số
# nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 3). Sau đó hãy tính tổng của toàn bộ
# tensor, array, tiếp theo tính tổng theo chiều dọc, chiều ngang . Lưu ý: sử dụng seed=2024

import numpy as np
import torch
import tensorflow as tf

# Set seed = 2024
SEED = 2024
np.random.seed(SEED)
torch.manual_seed(SEED)
tf.random.set_seed(SEED)

# Tạo 2 Numpy array, Pytorch tensor, Tensorflow tensor với giá trị ngẫu nhiên
np_array = np.random.randint(-10, 10, size=(3, 3))

torch_tensor = torch.randint(-10, 10, size=(3, 3))

tf_tensor = tf.random.uniform(minval=-10, maxval=10, shape=(3, 3))

# Tính tổng của toàn bộ tensor, array
np_total_sum = np.sum(np_array)
torch_total_sum = torch.sum(torch_tensor)
tf_total_sum = tf.reduce_sum(tf_tensor)

# Tính tổng theo chiều dọc
np_column_sum = np.sum(np_array, axis=0)
torch_column_sum = torch.sum(torch_tensor, axis=0)
tf_column_sum = tf.reduce_sum(tf_tensor, axis=0)

# Tính tổng theo chiều ngang
np_row_sum = np.sum(np_array, axis=1)
torch_row_sum = torch.sum(torch_tensor, axis=1)
tf_row_sum = tf.reduce_sum(tf_tensor, axis=1)

print(np_total_sum)
print(torch_total_sum)
print(tf_total_sum)
print("----------------------------")
print("Tổng theo chiều dọc")
print("----------------------------")
print(np_column_sum)
print(torch_column_sum)
print(tf_column_sum)
print("----------------------------")
print("Tổng theo chiều ngang")
print("----------------------------")
print(np_row_sum)
print(torch_row_sum)
print(tf_row_sum)

-53
tensor(-27)
tf.Tensor(-9.564312, shape=(), dtype=float32)
----------------------------
Tổng theo chiều dọc
----------------------------
[-15 -11 -27]
tensor([ -8,  -6, -13])
tf.Tensor([ 13.8027115  -9.312108  -14.054916 ], shape=(3,), dtype=float32)
----------------------------
Tổng theo chiều ngang
----------------------------
[-22 -16 -15]
tensor([ -4, -27,   4])
tf.Tensor([ -0.8886671   2.9121876 -11.587833 ], shape=(3,), dtype=float32)
