In [2]:
import numpy as np
import tensorflow as tf
import torch

In [6]:
"""
Câu 1: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor trong khoảng [0, 10)
với step=1?
"""
# Numpy array
np_array = np.arange(0, 10, 1)
print("Numpy array: ", np_array)

# Tensorflow tensor
tf_tensor = tf.range(0, 10, 1)
print("Tensorflow tensor: ", tf_tensor)

# Pytorch tensor
pt_tensor = torch.arange(0, 10, 1)
print("Pytorch tensor: ", pt_tensor)

Numpy array:  [0 1 2 3 4 5 6 7 8 9]
Tensorflow tensor:  tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
Pytorch tensor:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [5]:
"""
Câu 2: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor là ma trận đơn vị
với kích thước (3, 3).
"""
# Numpy unit matrix
np_unit_matrix = np.eye(3, 3)
print("Numpy unit matrix: ", np_unit_matrix)

# Tensorflow unit matrix
tf_unit_matrix = tf.eye(3, 3)
print("Tensorflow unit matrix: ", tf_unit_matrix)

# Pytorch unit matrix
pt_unit_matrix = torch.eye(3, 3)
print("Pytorch unit matrix: ", pt_unit_matrix)

Numpy unit matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Tensorflow unit matrix:  tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
Pytorch unit matrix:  tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [4]:
"""
Câu 3: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor ngẫu nhiên trong
khoảng giá trị [0, 1] với kích thước (3, 4). Tiếp theo hãy tạo array, tensor với các giá trị là số nguyên
trong khoảng [-10, 10]. Lưu ý trong bài tập này, các bạn sẽ sử dụng seed = 2024 để dảm bảo ra kết quả
giống đáp án, cách sử dụng như sau:
# Numpy code
import numpy as np
np.random.seed(2024)

# Pytorch code
import torch
torch.manual_seed(2024)

# Tensorflow code
import tensorflow as tf
tf.random.set_seed(2024)
"""
# Numpy random matrix
np.random.seed(2024)
np_random_matrix = np.random.rand(3, 4)
print("Numpy random matrix: ", np_random_matrix)

# Numpy random integer matrix
np_random_int_matrix = np.random.randint(-10, 10, (3, 4))
print("Numpy random integer matrix: ", np_random_int_matrix)

# Tensorflow random matrix
tf.random.set_seed(2024)
tf_random_matrix = tf.random.uniform((3, 4))
print("Tensorflow random matrix: ", tf_random_matrix)

# Tensorflow random integer matrix
tf_random_int_matrix = tf.random.uniform((3, 4), -10, 10, dtype=tf.int32)
print("Tensorflow random integer matrix: ", tf_random_int_matrix)

# Pytorch random matrix
torch.manual_seed(2024)
pt_random_matrix = torch.rand(3, 4)
print("Pytorch random matrix: ", pt_random_matrix)

# Pytorch random integer matrix
pt_random_int_matrix = torch.randint(-10, 10, (3, 4))
print("Pytorch random integer matrix: ", pt_random_int_matrix)

Numpy random matrix:  [[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]
Numpy random integer matrix:  [[ 5  1 -3  8]
 [-1 -4  0 -9]
 [-5  9 -6 -2]]
Tensorflow random matrix:  tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)
Tensorflow random integer matrix:  tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)
Pytorch random matrix:  tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])
Pytorch random integer matrix:  tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])
